name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - run: make test
